package com.train.services;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.train.Entity.User;
import com.train.dao.UserDao;
import com.train.dtos.UserDTO;

@Transactional // this annotation ensures that the entire class is executed within a single transaction
@Service // annotation that indicates this is a service class
public class AdminServiceImpl {

	@Autowired // this annotation injects a bean of type UserDao, which is automatically generated by Spring Boot
	private UserDao userDao;

	public User findUserByEmail(String email) {
		return userDao.findByEmail(email); // retrieves a user from the database by email
	}

	public List<User> findAllAdmins() {
		return userDao.findByRole("ADMIN"); // retrieves all users from the database who are admins
	}

	public User findAdminByEmailAndPassword(String email, String password) {
		User user = userDao.findByEmail(email); // retrieves a user from the database by email
		if (user != null && "ADMIN".equals(user.getRole()) && password.equals(user.getPassword())) {
			return user;
		}
		return null;
	}

	public User saveAdmin(User admin) {
		return userDao.save(admin); // saves an admin to the database
	}

	public User updateAdmin(int id, UserDTO update) {
		User user = userDao.getById(id); // retrieves a user from the database by id
		if (user != null && "ADMIN".equals(user.getRole())) { // if the user is an admin
			user.setFirstName(update.getFirstName()); // update the first name
			user.setLastName(update.getLastName()); // update the last name
			user.setEmail(update.getEmail()); // update the email
			user.setAddress(update.getAddress()); // update the address
			user.setPhone(update.getPhone()); // update the phone number
			return userDao.save(user); // saves the updated admin to the database
		}
		return null;
	}
}




//package com.train.services;
//
//import java.util.List;
//
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.stereotype.Service;
//import org.springframework.transaction.annotation.Transactional;
//
//import com.train.Entity.User;
//import com.train.dao.UserDao;
//import com.train.dtos.UserDTO;
//
//@Transactional
//@Service
//public class AdminServiceImpl {
//
//	@Autowired
//	private UserDao userDao;
//
//	public User findUserByEmail(String email) {
//		return userDao.findByEmail(email);
//	}
//
//	public List<User> findAllAdmins() {
//		return userDao.findByRole("ADMIN");
//	}
//
//	public User findAdminByEmailAndPassword(String email, String password) {
//		User user = userDao.findByEmail(email);
//		if (user != null && "ADMIN".equals(user.getRole()) && password.equals(user.getPassword())) {
//			return user;
//		}
//		return null;
//	}
//
//	public User saveAdmin(User admin) {
//		return userDao.save(admin);
//	}
//
//	public User updateAdmin(int id, UserDTO update) {
//		User user = userDao.getById(id);
//		if (user != null && "ADMIN".equals(user.getRole())) {
//			user.setFirstName(update.getFirstName());
//			user.setLastName(update.getLastName());
//			user.setEmail(update.getEmail());
//			user.setAddress(update.getAddress());
//			user.setPhone(update.getPhone());
//			return userDao.save(user);
//		}
//		return null;
//	}
//}
//
////package com.train.services;
////
////import java.util.List;
////
////import org.springframework.beans.factory.annotation.Autowired;
////import org.springframework.stereotype.Service;
////import org.springframework.transaction.annotation.Transactional;
////
////import com.train.Entity.Admin;
////import com.train.Entity.User;
////import com.train.dao.AdminDao;
////import com.train.dtos.AdminDto;
////
////@Transactional
////@Service
////public class AdminServiceImpl {
////
////	@Autowired
////	private AdminDao adminDao;
////	
////	public Admin findAdminByEmail(String email)
////	{
////		return adminDao.findAdminByEmail(email);
////	}
////	
////	public List<Admin> findAllAdmins() {
////		return adminDao.findAll();
////	}
////	
////	public Admin findAdminByEmailAndPassword(String email, String password) {
////		Admin admin = adminDao.findAdminByEmail(email);
////		if(admin!= null && password.equals(admin.getPassword()))
////			return admin;
////		return null;
////	}
////
////	public Admin saveAdmin(Admin admin) {
////		Admin result=adminDao.save(admin);
////		return result;
////	}
////
////	public Admin UpdateAdmin(int id, AdminDto update) {
////		Admin admin= adminDao.getById(id);
////		 if(admin !=null)
////		   {
////			 admin.setFirstName(update.getFirstName());
////			 admin.setLastName(update.getLastName());
////			 admin.setEmail(update.getEmail());
////			 
////			 admin.setAddress(update.getAddress());
////			 admin.setPhone(update.getPhone());
////			   
////			   Admin updatedAdmin= adminDao.save(admin);
////			   return updatedAdmin ;
////		   }
////		   else
////			  return null ;
////		
////	}
////}
